/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/community/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게시글 목록·검색
     * @description category(선택)·keyword(선택, 제목·본문 검색)·sort(latest/popular/accuracy)로 필터·정렬해 페이지네이션한다. 삭제된 글은 제외된다. 이 API는 본인 식별을 쓰지 않지만 인증은 필요하다.
     */
    get: operations['getPosts'];
    put?: never;
    /**
     * 게시글 작성
     * @description category·title·content(필수)로 게시글을 작성한다. 작성 언어는 현재 "ko"로 고정된다(인증/locale 연동 전).
     */
    post: operations['createPost'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/posts/{id}/likes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 관심글 저장(좋아요)
     * @description 게시글 public_id로 좋아요를 저장한다. like_count +1, 성공 시 201. 이미 좋아요한 글이면 409 COMMON4091, 없거나 삭제된 글이면 404 COMMUNITY4001. 응답 바디는 post_public_id/like_count/liked를 반환한다.
     */
    post: operations['like'];
    /**
     * 관심글 취소(좋아요 취소)
     * @description 게시글 public_id의 좋아요를 취소한다. like_count -1, 성공 시 200. 없거나 삭제된 글이면 404 COMMUNITY4001. 안 누른 글을 취소하면 멱등 no-op로 200(like_count 변화 없음).
     */
    delete: operations['unlike'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/posts/{id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 댓글 목록 조회
     * @description 게시글 public_id에 달린 댓글을 작성순(오래된 순)으로 페이지네이션해 반환한다. 삭제된 댓글은 제외된다. 없거나 삭제된 게시글이면 404 COMMUNITY4001. 이 API는 본인 식별을 쓰지 않지만 인증은 필요하다. 대댓글은 별도 이슈로, 현재 parent_comment_public_id는 항상 null이다.
     */
    get: operations['getComments'];
    put?: never;
    /**
     * 댓글 작성
     * @description 게시글에 댓글을 작성한다. 작성자는 JWT public_id claim에서 식별된다. 작성 성공 시 게시글의 comment_count가 1 증가한다. 대댓글은 본 사이클 범위 밖 — 모든 댓글이 최상위로 INSERT된다(parent_comment_public_id 응답은 항상 null). 없거나 삭제된 게시글이면 404 COMMUNITY4001.
     */
    post: operations['createComment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/posts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게시글 단건 조회
     * @description 게시글 public_id로 본문 + 작성자(닉네임/인증배지) + 카운트를 반환한다. 삭제됐거나 없는 글이면 404 COMMUNITY4001.
     */
    get: operations['getPost'];
    put?: never;
    post?: never;
    /**
     * 게시글 삭제
     * @description 본인 게시글을 soft delete(deleted_at 세팅)한다. 타인 글이면 403 COMMON4031, 없는 글이면 404 COMMUNITY4001. 성공 시 200 + data:null.
     */
    delete: operations['deletePost'];
    options?: never;
    head?: never;
    /**
     * 게시글 수정
     * @description 본인 게시글의 category/title/content를 부분 수정한다(보낸 필드만 변경). 타인 글이면 403 COMMON4031, 없는 글이면 404 COMMUNITY4001.
     */
    patch: operations['updatePost'];
    trace?: never;
  };
  '/api/v1/community/qna': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 주요 QnA 목록
     * @description 특정 카테고리의 활성 게시글을 답변(댓글) 수 내림차순으로 상위 N건 반환한다. page 메타는 없다(Top N 고정). 작성자 정보·본문은 응답에 포함하지 않으며 단건 조회 API로 별도 조회한다. category 미입력 시 QUESTION 카테고리만, 입력 시 해당 카테고리만 반환한다 (LIFE_INFO/JOB/VISA/COUNTRY/RESIDENCE/QUESTION). 잘못된 카테고리는 400 COMMON4001. 본 API는 **인증 불필요** — 비로그인 사용자도 호출 가능.
     */
    get: operations['getQnaPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/posts/liked': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 관심글 목록 조회
     * @description 요청자가 좋아요한 게시글 목록을 sort(latest=좋아요 누른 시각순 / popular=좋아요 수순, 기본 latest)로 정렬해 페이지네이션한다. 각 항목에 liked_at(좋아요 누른 시각)이 포함된다. 삭제된 글은 제외된다.
     */
    get: operations['getLikedPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/community/posts/{postId}/comments/{commentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 댓글 삭제
     * @description 본인이 작성한 댓글을 soft delete한다(deleted_at만 갱신, row 보존). 삭제 성공 시 게시글의 comment_count가 1 감소한다(같은 트랜잭션 내). 응답 body는 data: null. 본인이 아닌 경우 403 COMMON4031. 이미 삭제된 댓글의 재삭제는 404 COMMUNITY4002로 응답한다(deleted_at IS NULL 필터). URL의 postId와 댓글의 실제 게시글이 다르면 404 COMMUNITY4002로 통일.
     */
    delete: operations['deleteComment'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PostCreateRequest: {
      /**
       * @description 카테고리
       * @example JOB
       * @enum {string}
       */
      category: 'LIFE_INFO' | 'JOB' | 'VISA' | 'COUNTRY' | 'RESIDENCE' | 'QUESTION';
      /**
       * @description 제목
       * @example 시급 9,000원 받고 일했는데 최저임금 미달인가요?
       */
      title: string;
      /**
       * @description 본문
       * @example 베트남에서 온 외국인입니다. 같은 경험 있는 분 계시면 알려주세요.
       */
      content: string;
    };
    /** @description 공통 실패 응답. 성공 응답과 달리 data 키가 없고 비즈니스 code가 포함된다. */
    ErrorResponse: {
      /**
       * @description 성공 여부. 실패 응답에선 항상 false.
       * @example false
       */
      success?: boolean;
      /**
       * @description 비즈니스 에러 코드({DOMAIN}{4자리}).
       * @example WALLET4001
       */
      code?: string;
      /**
       * @description 사용자에게 보여줄 에러 메시지.
       * @example 존재하지 않는 지갑입니다.
       */
      message?: string;
    };
    ApiResponsePostDetailResponse: {
      success?: boolean;
      data?: components['schemas']['PostDetailResponse'];
      message?: string;
    };
    PostDetailResponse: {
      /**
       * @description 게시글 UUID
       * @example a1b2c3d4-0000-0000-0000-000000000001
       */
      publicId?: string;
      /**
       * @description 카테고리
       * @example JOB
       * @enum {string}
       */
      category?: 'LIFE_INFO' | 'JOB' | 'VISA' | 'COUNTRY' | 'RESIDENCE' | 'QUESTION';
      /**
       * @description 제목
       * @example 시급 9,000원 받고 일했는데 최저임금 미달인가요?
       */
      title?: string;
      /**
       * @description 본문(전체)
       * @example 베트남에서 온 외국인입니다. 같은 경험 있는 분 계시면 알려주세요.
       */
      content?: string;
      /**
       * @description 작성자 닉네임
       * @example Minh
       */
      authorNickname?: string;
      /**
       * @description 작성자 인증 배지 여부
       * @example true
       */
      authorIsVerified?: boolean;
      /**
       * Format: int32
       * @description 좋아요 수
       * @example 3
       */
      likeCount?: number;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 2
       */
      commentCount?: number;
      /**
       * @description 작성 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      createdAt?: string;
      /**
       * @description 수정 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      updatedAt?: string;
    };
    ApiResponsePostLikeResponse: {
      success?: boolean;
      data?: components['schemas']['PostLikeResponse'];
      message?: string;
    };
    PostLikeResponse: {
      /**
       * @description 게시글 UUID
       * @example a1b2c3d4-0000-0000-0000-000000000001
       */
      postPublicId?: string;
      /**
       * Format: int32
       * @description 갱신된 좋아요 수
       * @example 4
       */
      likeCount?: number;
      /**
       * @description 요청자의 현재 좋아요 여부(저장=true, 취소=false)
       * @example true
       */
      liked?: boolean;
    };
    CreateCommentRequest: {
      /**
       * @description 댓글 내용 (1~2000자)
       * @example 좋은 정보 감사합니다!
       */
      content: string;
    };
    ApiResponseCommentResponse: {
      success?: boolean;
      data?: components['schemas']['CommentResponse'];
      message?: string;
    };
    CommentResponse: {
      /**
       * @description 댓글 UUID
       * @example c1d2e3f4-0000-0000-0000-000000000001
       */
      publicId?: string;
      /**
       * @description 게시글 UUID
       * @example a1b2c3d4-0000-0000-0000-000000000001
       */
      postPublicId?: string;
      /**
       * @description 부모 댓글 UUID(최상위면 null). 대댓글 미구현 — 현재 항상 null
       * @example null
       */
      parentCommentPublicId?: string;
      /**
       * @description 댓글 내용
       * @example 저도 작년에 똑같은 일 겪었어요. 노동부 1350에 신고해 차액 다 받았어요.
       */
      content?: string;
      /**
       * @description 작성자 닉네임
       * @example Minh
       */
      authorNickname?: string;
      /**
       * @description 작성자 인증 배지 여부
       * @example true
       */
      authorIsVerified?: boolean;
      /**
       * @description 작성 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      createdAt?: string;
    };
    PostUpdateRequest: {
      /**
       * @description 변경할 카테고리(선택)
       * @example QUESTION
       * @enum {string}
       */
      category?: 'LIFE_INFO' | 'JOB' | 'VISA' | 'COUNTRY' | 'RESIDENCE' | 'QUESTION';
      /**
       * @description 변경할 제목(선택)
       * @example 제목을 수정합니다
       */
      title?: string;
      /**
       * @description 변경할 본문(선택)
       * @example 본문을 수정합니다
       */
      content?: string;
    };
    ApiResponseQnaListResponse: {
      success?: boolean;
      data?: components['schemas']['QnaListResponse'];
      message?: string;
    };
    QnaListResponse: {
      /** @description QnA 게시글 목록 (답변 수 내림차순) */
      posts?: components['schemas']['QnaPostResponse'][];
    };
    QnaPostResponse: {
      /**
       * @description 게시글 UUID
       * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
       */
      publicId?: string;
      /**
       * @description 제목
       * @example E-9 비자로 근무지 변경이 가능한가요?
       */
      title?: string;
      /**
       * Format: int32
       * @description 답변(댓글) 수
       * @example 7
       */
      commentCount?: number;
      /**
       * @description 작성 시각(ISO 8601, UTC Z)
       * @example 2026-05-20T09:00:00Z
       */
      createdAt?: string;
    };
    ApiResponsePostListResponse: {
      success?: boolean;
      data?: components['schemas']['PostListResponse'];
      message?: string;
    };
    PostListResponse: {
      /** @description 게시글 목록 */
      posts?: components['schemas']['PostSummaryResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지(0부터)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지당 게시글 수
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 게시글 수
       * @example 42
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 3
       */
      totalPages?: number;
    };
    PostSummaryResponse: {
      /**
       * @description 게시글 UUID
       * @example a1b2c3d4-0000-0000-0000-000000000001
       */
      publicId?: string;
      /**
       * @description 카테고리
       * @example JOB
       * @enum {string}
       */
      category?: 'LIFE_INFO' | 'JOB' | 'VISA' | 'COUNTRY' | 'RESIDENCE' | 'QUESTION';
      /**
       * @description 제목
       * @example 시급 9,000원 받고 일했는데 최저임금 미달인가요?
       */
      title?: string;
      /**
       * @description 본문 미리보기(앞 100자, 초과 시 … 표기)
       * @example 베트남에서 온 외국인입니다. 같은 경험 있는 분 계시면…
       */
      contentPreview?: string;
      /**
       * @description 작성자 닉네임
       * @example Minh
       */
      authorNickname?: string;
      /**
       * Format: int32
       * @description 좋아요 수
       * @example 3
       */
      likeCount?: number;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 2
       */
      commentCount?: number;
      /**
       * @description 작성 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      createdAt?: string;
    };
    ApiResponseCommentListResponse: {
      success?: boolean;
      data?: components['schemas']['CommentListResponse'];
      message?: string;
    };
    CommentListResponse: {
      /** @description 댓글 목록(작성순) */
      comments?: components['schemas']['CommentResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지(0부터)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지당 댓글 수
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 댓글 수
       * @example 2
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 1
       */
      totalPages?: number;
    };
    ApiResponseLikedPostListResponse: {
      success?: boolean;
      data?: components['schemas']['LikedPostListResponse'];
      message?: string;
    };
    LikedPostListResponse: {
      /** @description 관심글 목록 */
      posts?: components['schemas']['LikedPostSummaryResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지(0부터)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지당 게시글 수
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 관심글 수
       * @example 5
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 1
       */
      totalPages?: number;
    };
    LikedPostSummaryResponse: {
      /**
       * @description 게시글 UUID
       * @example a1b2c3d4-0000-0000-0000-000000000001
       */
      publicId?: string;
      /**
       * @description 카테고리
       * @example JOB
       * @enum {string}
       */
      category?: 'LIFE_INFO' | 'JOB' | 'VISA' | 'COUNTRY' | 'RESIDENCE' | 'QUESTION';
      /**
       * @description 제목
       * @example 시급 9,000원 받고 일했는데 최저임금 미달인가요?
       */
      title?: string;
      /**
       * @description 본문 미리보기(앞 100자, 초과 시 … 표기)
       * @example 베트남에서 온 외국인입니다. 같은 경험 있는 분 계시면…
       */
      contentPreview?: string;
      /**
       * @description 작성자 닉네임
       * @example Minh
       */
      authorNickname?: string;
      /**
       * Format: int32
       * @description 좋아요 수
       * @example 3
       */
      likeCount?: number;
      /**
       * Format: int32
       * @description 댓글 수
       * @example 2
       */
      commentCount?: number;
      /**
       * @description 작성 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      createdAt?: string;
      /**
       * @description 좋아요 누른 시각(ISO 8601, UTC Z)
       * @example 2026-05-27T09:30:00Z
       */
      likedAt?: string;
    };
    ApiResponseVoid: {
      success?: boolean;
      data?: unknown;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getPosts: {
    parameters: {
      query?: {
        category?: string;
        keyword?: string;
        sort?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 PostListResponse(posts + 페이지 메타)가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePostListResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 category/sort 값 또는 page/size 범위 위반. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PostCreateRequest'];
      };
    };
    responses: {
      /** @description 작성 성공. data에 PostDetailResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePostDetailResponse'];
        };
      };
      /** @description COMMON4001 - 필수값 누락 또는 잘못된 category 값. (공통 검증 핸들러가 Bean Validation 실패를 COMMON4001로 통일한다.) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  like: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저장 성공. data에 PostLikeResponse(like_count 갱신값, liked=true)가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePostLikeResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 요청(public_id 형식 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4091 - 이미 좋아요한 게시글입니다(중복). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  unlike: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 취소 성공(또는 멱등 no-op). data에 PostLikeResponse(liked=false)가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePostLikeResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 요청(public_id 형식 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getComments: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 CommentListResponse(comments + 페이지 메타)가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCommentListResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 page/size 범위 위반, public_id 형식 위반. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCommentRequest'];
      };
    };
    responses: {
      /** @description 작성 성공. data에 CommentResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCommentResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 요청 (content 빈값/길이 초과/path variable 형식 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getPost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 PostDetailResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePostDetailResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 요청(public_id 형식 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deletePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공. data는 null. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description COMMON4001 - 잘못된 요청(public_id 형식 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 본인 게시글이 아닙니다(권한 없음). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updatePost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PostUpdateRequest'];
      };
    };
    responses: {
      /** @description 수정 성공. data에 갱신된 PostDetailResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePostDetailResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 category 값 또는 입력 형식 오류. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 본인 게시글이 아닙니다(권한 없음). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getQnaPosts: {
    parameters: {
      query?: {
        category?: string;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data.posts는 답변 수 내림차순 정렬된 배열(최대 size건). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseQnaListResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 카테고리 / size 범위 위반 (1~100). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getLikedPosts: {
    parameters: {
      query?: {
        sort?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 LikedPostListResponse(posts + 페이지 메타)가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLikedPostListResponse'];
        };
      };
      /** @description COMMON4001 - 잘못된 sort 값 또는 page/size 범위 위반. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        postId: string;
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공. data는 null. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description COMMON4001 - path variable 형식 위반(빈값/36자 초과). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 본인이 작성한 댓글이 아닙니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMUNITY4001 - 존재하지 않는 게시글입니다. / COMMUNITY4002 - 존재하지 않는 댓글입니다(미존재·이미 삭제됨·URL 불일치). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
