/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 분석 요청 목록 조회
     * @description 본인이 제출한 분석 요청을 최근순으로 페이지 조회한다. 기본 페이지 크기 20, 정렬 createdAt DESC.
     */
    get: operations['list'];
    put?: never;
    /**
     * 문서 분석 요청
     * @description 분석 대상 문서 종류와 파일명을 받아 분석 요청을 생성하고, 사용자가 원본 파일을 업로드할 S3 Pre-signed PUT URL을 발급한다. Pre-signed URL은 약 10분 동안 유효하다.
     */
    post: operations['submit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{publicId}/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['chat'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{publicId}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 분석 진행 상태 조회
     * @description 프론트가 폴링하는 가벼운 엔드포인트. ANALYZING/COMPLETED/FAILED 중 하나를 반환한다.
     */
    get: operations['getStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/documents/{publicId}/result': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 분석 결과 상세 조회
     * @description 분석이 완료된(또는 PARTIAL) 문서의 상세 결과를 반환한다. 결과가 아직 없는 경우(ANALYZING/결과 미생성) 422.
     */
    get: operations['getResult'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SubmitRequest: {
      /**
       * @description 분석 대상 문서 종류
       * @example LABOR_CONTRACT
       * @enum {string}
       */
      analysisDocumentType: 'LABOR_CONTRACT' | 'PAYSLIP' | 'EMPLOYMENT_CONTRACT';
      /**
       * @description 사용자 업로드 원본 파일명
       * @example contract.pdf
       */
      fileName: string;
    };
    /** @description 공통 실패 응답. 성공 응답과 달리 data 키가 없고 비즈니스 code가 포함된다. */
    ErrorResponse: {
      /**
       * @description 성공 여부. 실패 응답에선 항상 false.
       * @example false
       */
      success?: boolean;
      /**
       * @description 비즈니스 에러 코드({DOMAIN}{4자리}).
       * @example WALLET4001
       */
      code?: string;
      /**
       * @description 사용자에게 보여줄 에러 메시지.
       * @example 존재하지 않는 지갑입니다.
       */
      message?: string;
    };
    ApiResponseSubmissionResponse: {
      success?: boolean;
      data?: components['schemas']['SubmissionResponse'];
      message?: string;
    };
    SubmissionResponse: {
      /**
       * @description 분석 요청 식별자(public_id). 이후 상태/결과 조회 시 사용.
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      publicId?: string;
      /**
       * @description 현재 분석 상태
       * @example ANALYZING
       * @enum {string}
       */
      status?: 'ANALYZING' | 'COMPLETED' | 'FAILED';
      /**
       * @description Pre-signed PUT URL.
       * @example https://s3.ap-northeast-2.amazonaws.com/...
       */
      uploadUrl?: string;
      /**
       * @description uploadUrl로 PUT 업로드할 때 그대로 함께 보내야 하는 헤더(이름+값). 서명에 포함되어 있어 누락/변경 시 403이 나고 메타데이터가 오브젝트에 박히지 않는다.
       * @example {
       *       "Content-Type": "application/octet-stream",
       *       "x-amz-meta-source": "production",
       *       "x-amz-meta-document_id": "550e8400-e29b-41d4-a716-446655440000"
       *     }
       */
      uploadHeaders?: {
        [key: string]: string;
      };
      /**
       * @description uploadUrl 만료 시각(ISO 8601 UTC Z).
       * @example 2026-05-29T10:00:00Z
       */
      expiresAt?: string;
    };
    ChatRequest: {
      message: string;
      sessionId?: string;
      userLang: string;
    };
    SseEmitter: {
      /** Format: int64 */
      timeout?: number;
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    ApiResponsePageDocumentSummaryResponse: {
      success?: boolean;
      data?: components['schemas']['PageDocumentSummaryResponse'];
      message?: string;
    };
    DocumentSummaryResponse: {
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      publicId?: string;
      analysisDocumentType?: string;
      fileName?: string;
      status?: string;
      overallRiskLevel?: string;
      createdAt?: string;
    };
    PageDocumentSummaryResponse: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['DocumentSummaryResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components['schemas']['SortObject'];
      paged?: boolean;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      pageNumber?: number;
      unpaged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      sorted?: boolean;
      unsorted?: boolean;
    };
    ApiResponseDocumentStatusResponse: {
      success?: boolean;
      data?: components['schemas']['DocumentStatusResponse'];
      message?: string;
    };
    DocumentStatusResponse: {
      /**
       * @description 분석 요청 public_id
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      publicId?: string;
      /**
       * @description 현재 분석 상태
       * @example ANALYZING
       * @enum {string}
       */
      status?: 'ANALYZING' | 'COMPLETED' | 'FAILED';
      /**
       * Format: int32
       * @description 분석 중일 때 표시할 예상 남은 분(고정값). 완료/실패면 0.
       * @example 3
       */
      estimatedMinutes?: number;
    };
    ApiResponseDocumentResultResponse: {
      success?: boolean;
      data?: components['schemas']['DocumentResultResponse'];
      message?: string;
    };
    DeductionDto: {
      name?: string;
      amount?: string;
    };
    DocumentResultResponse: {
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      documentPublicId?: string;
      /** @enum {string} */
      analysisDocumentType?: 'LABOR_CONTRACT' | 'PAYSLIP' | 'EMPLOYMENT_CONTRACT';
      /** @enum {string} */
      processingStatus?: 'COMPLETED' | 'FAILED' | 'PARTIAL';
      /** @enum {string} */
      overallRiskLevel?: 'LOW' | 'MEDIUM' | 'HIGH';
      /**
       * @description OCR 신뢰도. 표시 전용 number.
       * @example 0.92
       */
      ocrConfidence?: number;
      wageSummary?: components['schemas']['WageSummaryDto'];
      riskItems?: components['schemas']['RiskItemDto'][];
      translatedText?: string;
      translatedLang?: string;
      maskedFileUrl?: string;
      failedReason?: string;
      completedAt?: string;
      createdAt?: string;
      updatedAt?: string;
    };
    RiskItemDto: {
      riskLevel?: string;
      clause?: string;
      description?: string;
    };
    WageSummaryDto: {
      currencyCode?: string;
      monthlyWage?: string;
      hourlyWage?: string;
      deductions?: components['schemas']['DeductionDto'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable'];
      };
      header: {
        'X-User-Public-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data는 Spring Page 구조(content, totalElements, totalPages, ...). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponsePageDocumentSummaryResponse'];
        };
      };
      /** @description COMMON4001 - X-User-Public-Id 헤더 누락(필수 헤더 미전송). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  submit: {
    parameters: {
      query?: never;
      header: {
        'X-User-Public-Id': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitRequest'];
      };
    };
    responses: {
      /** @description 생성 성공. data에 SubmissionResponse(public_id, upload_url, expires_at). */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSubmissionResponse'];
        };
      };
      /** @description COMMON4001 - 요청 본문 검증 실패(파일명 형식/필드 누락 등) 또는 X-User-Public-Id 헤더 누락. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  chat: {
    parameters: {
      query?: never;
      header: {
        'X-User-Public-Id': string;
      };
      path: {
        publicId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': components['schemas']['SseEmitter'];
        };
      };
    };
  };
  getStatus: {
    parameters: {
      query?: never;
      header: {
        'X-User-Public-Id': string;
      };
      path: {
        publicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseDocumentStatusResponse'];
        };
      };
      /** @description COMMON4001 - X-User-Public-Id 헤더 누락(필수 헤더 미전송). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 다른 사용자의 문서. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description DOCUMENT4001 - 존재하지 않는 문서. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getResult: {
    parameters: {
      query?: never;
      header: {
        'X-User-Public-Id': string;
      };
      path: {
        publicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 DocumentResultResponse. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseDocumentResultResponse'];
        };
      };
      /** @description COMMON4001 - X-User-Public-Id 헤더 누락(필수 헤더 미전송). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 다른 사용자의 문서. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description DOCUMENT4001 - 존재하지 않는 문서. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4221 - 분석 결과가 아직 없습니다. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
