/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/members/me/social-profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 소셜 가입 후 추가 정보 보완
     * @description Google 등 소셜 로그인으로 처음 가입한 회원이 닉네임/국적/언어를 입력해 가입을 완료한다. 이메일·이름은 토큰(JWT claim)에서 채우며, 이 요청이 성공하면 회원(members) 정보가 최초 생성된다. 이미 완료된 회원이 다시 호출하면 COMMON4091로 거절한다.
     */
    post: operations['completeSocialProfile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 회원가입
     * @description 이메일, 비밀번호, 이름, 닉네임, 국적, 주 사용 언어로 회원가입한다.
     */
    post: operations['signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 비밀번호 재설정
     * @description 메일 링크의 토큰과 새 비밀번호로 비밀번호를 변경한다(IdP 경유).
     */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password/reset-request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 비밀번호 재설정 링크 발송
     * @description 가입 이메일로 비밀번호 재설정 링크를 발송한다. 가입 여부 노출 방지를 위해 미가입 이메일이어도 동일하게 200을 반환한다(실제 발송은 가입된 경우만).
     */
    post: operations['sendPasswordResetEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 프로필 조회
     * @description 마이페이지 내 프로필을 조회한다. is_verified/temperature_grade/profile_image_url은 각각 인증·커뮤니티·이미지 도메인 소관이라 현재 기본값으로 내려간다.
     */
    get: operations['getMyProfile'];
    put?: never;
    post?: never;
    /**
     * 회원 탈퇴
     * @description 현재 로그인한 회원을 탈퇴 처리한다. 로컬은 soft delete(deleted_at)로 보존하고, 외부 IdP(Authentik) 사용자는 비활성화(is_active=false)해 이후 로그인/토큰 발급을 막는다.
     */
    delete: operations['withdraw'];
    options?: never;
    head?: never;
    /**
     * 내 프로필 수정
     * @description 닉네임/주 사용 언어/자기소개를 수정한다. 닉네임을 다른 값으로 바꿀 때만 중복 확인한다.
     */
    patch: operations['updateMyProfile'];
    trace?: never;
  };
  '/api/v1/members/me/language': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 언어 설정 조회
     * @description 현재 로그인한 회원의 주 사용 언어(BCP 47)를 조회한다.
     */
    get: operations['getLanguage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 언어 설정 변경
     * @description 현재 로그인한 회원의 주 사용 언어(BCP 47)를 변경하고 변경된 값을 반환한다.
     */
    patch: operations['updateLanguage'];
    trace?: never;
  };
  '/api/v1/members/check-nickname': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 닉네임 중복 확인
     * @description 닉네임이 사용 가능한지(중복이 아닌지) 확인한다. available=true면 사용 가능.
     */
    get: operations['checkNickname'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/check-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 이메일 중복 확인
     * @description 이메일이 사용 가능한지(중복이 아닌지) 확인한다. available=true면 사용 가능.
     */
    get: operations['checkEmail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SocialProfileRequest: {
      /**
       * @description 닉네임 (앱 전체에서 중복 불가)
       * @example gildong
       */
      nickname: string;
      /**
       * @description 국적 (ISO 3166-1 alpha-2, 예: VN)
       * @example VN
       */
      nationality: string;
      /**
       * @description 주 사용 언어 (BCP 47 소문자, 예: vi)
       * @example vi
       */
      language: string;
    };
    /** @description 공통 실패 응답. 성공 응답과 달리 data 키가 없고 비즈니스 code가 포함된다. */
    ErrorResponse: {
      /**
       * @description 성공 여부. 실패 응답에선 항상 false.
       * @example false
       */
      success?: boolean;
      /**
       * @description 비즈니스 에러 코드({DOMAIN}{4자리}).
       * @example WALLET4001
       */
      code?: string;
      /**
       * @description 사용자에게 보여줄 에러 메시지.
       * @example 존재하지 않는 지갑입니다.
       */
      message?: string;
    };
    ApiResponseSocialProfileResponse: {
      success?: boolean;
      data?: components['schemas']['SocialProfileResponse'];
      message?: string;
    };
    SocialProfileResponse: {
      publicId?: string;
      email?: string;
      nickname?: string;
    };
    SignupRequest: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
      nickname: string;
      nationality: string;
      language: string;
    };
    ApiResponseSignupResponse: {
      success?: boolean;
      data?: components['schemas']['SignupResponse'];
      message?: string;
    };
    SignupResponse: {
      publicId?: string;
      email?: string;
      nickname?: string;
    };
    PasswordResetRequest: {
      /**
       * @description 재설정 링크에 포함된 토큰
       * @example 9f8e7d6c-1234-5678-abcd-ef0123456789
       */
      token: string;
      /**
       * @description 새 비밀번호
       * @example NewP@ssw0rd!
       */
      newPassword: string;
    };
    ApiResponseVoid: {
      success?: boolean;
      data?: unknown;
      message?: string;
    };
    PasswordResetEmailRequest: {
      /**
       * Format: email
       * @description 재설정 링크를 받을 가입 이메일
       * @example user@example.com
       */
      email: string;
    };
    ProfileUpdateRequest: {
      /**
       * @description 닉네임
       * @example global_neighbor
       */
      nickname: string;
      /**
       * @description 주 사용 언어(BCP 47)
       * @example ko
       */
      language: string;
      /**
       * @description 자기소개(한 줄 소개). 선택값
       * @example 안녕하세요.
       */
      bio?: string;
    };
    ApiResponseProfileResponse: {
      success?: boolean;
      data?: components['schemas']['ProfileResponse'];
      message?: string;
    };
    ProfileResponse: {
      /** @description 회원 식별자(UUID) */
      publicId?: string;
      /** @description 이메일 */
      email?: string;
      /**
       * @description 닉네임
       * @example global_neighbor
       */
      nickname?: string;
      /**
       * @description 국적 코드(ISO 3166-1 alpha-2)
       * @example VN
       */
      nationality?: string;
      /**
       * @description 주 사용 언어(BCP 47)
       * @example ko
       */
      language?: string;
      /** @description 자기소개(한 줄 소개). 미입력 시 null */
      bio?: string;
      /** @description 신분증 인증 배지 여부. (현재 기본 false — 인증 도메인 구현 시 실제 값) */
      isVerified?: boolean;
      /** @description 커뮤니티 매너온도 등급(RED/YELLOW/GREEN/PURPLE/BLUE). (현재 기본값 — 커뮤니티 도메인 구현 시 실제 값) */
      temperatureGrade?: string;
      /** @description 프로필 사진 URL. 미설정 시 null */
      profileImageUrl?: string;
      /**
       * @description 가입 일시(ISO 8601, UTC Z)
       * @example 2026-06-03T18:21:08Z
       */
      createdAt?: string;
    };
    LanguageUpdateRequest: {
      /**
       * @description 변경할 주 사용 언어 (BCP 47)
       * @example ko
       */
      language: string;
    };
    ApiResponseLanguageResponse: {
      success?: boolean;
      data?: components['schemas']['LanguageResponse'];
      message?: string;
    };
    LanguageResponse: {
      /**
       * @description 주 사용 언어 (BCP 47)
       * @example vi
       */
      language?: string;
    };
    ApiResponseCheckAvailabilityResponse: {
      success?: boolean;
      data?: components['schemas']['CheckAvailabilityResponse'];
      message?: string;
    };
    CheckAvailabilityResponse: {
      /**
       * @description 사용 가능 여부 (true=사용 가능, false=이미 사용 중)
       * @example true
       */
      available?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  completeSocialProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SocialProfileRequest'];
      };
    };
    responses: {
      /** @description 보완 완료. data에 SocialProfileResponse(public_id/email/nickname). */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSocialProfileResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(@Valid 실패 등). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다(토큰 없음/무효 또는 식별 claim 누락). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4091 - 이미 가입 완료된 회원 / MEMBER4002 - 이메일 중복 / MEMBER4003 - 닉네임 중복. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest'];
      };
    };
    responses: {
      /** @description 가입 성공. 응답은 공통 ApiResponse로 감싸지며 data에 SignupResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSignupResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(@Valid 실패 등). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4002 - 이메일 중복 / MEMBER4003 - 닉네임 중복. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description 비밀번호 변경 완료. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description COMMON4001 - 요청 값 오류 / MEMBER4004 - 유효하지 않거나 만료된 재설정 토큰. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - IdP 비밀번호 변경 실패 등 서버 오류. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  sendPasswordResetEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetEmailRequest'];
      };
    };
    responses: {
      /** @description 요청 접수(가입된 이메일이면 메일 발송). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(이메일 형식 등). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 ProfileResponse. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseProfileResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4001 - 존재하지 않는 회원입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  withdraw: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 탈퇴 성공. data 는 null. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다.(토큰 누락/무효) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4001 - 존재하지 않는 회원입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - IdP 연동 실패로 탈퇴를 완료하지 못했습니다.(롤백) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updateMyProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileUpdateRequest'];
      };
    };
    responses: {
      /** @description 수정 성공. data에 변경된 ProfileResponse. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseProfileResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4001 - 존재하지 않는 회원입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4003 - 이미 사용 중인 닉네임입니다. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getLanguage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data.language 로 주 사용 언어 반환. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLanguageResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다.(토큰 누락/무효) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4001 - 존재하지 않는 회원입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updateLanguage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LanguageUpdateRequest'];
      };
    };
    responses: {
      /** @description 변경 성공. data.language 로 변경된 언어 반환. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseLanguageResponse'];
        };
      };
      /** @description COMMON4001 - 언어가 비어 있습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다.(토큰 누락/무효) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4001 - 존재하지 않는 회원입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  checkNickname: {
    parameters: {
      query: {
        nickname: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 확인 성공. data.available 로 사용 가능 여부 반환. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCheckAvailabilityResponse'];
        };
      };
      /** @description COMMON4001 - 닉네임이 비어 있습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  checkEmail: {
    parameters: {
      query: {
        email: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 확인 성공. data.available 로 사용 가능 여부 반환. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCheckAvailabilityResponse'];
        };
      };
      /** @description COMMON4001 - 이메일이 비었거나 형식이 올바르지 않습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
