/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/transfers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 송금 실행
     * @description INTERNAL_TRANSFER(앱 사용자 간 송금)를 실행한다. 1단계 범위는 같은 통화 송금만 — currency_code != receive_currency_code면 TRANSFER4005. REMITTANCE는 후속 PR에서 추가. Idempotency-Key 헤더로 멱등성 보장(3-layer: Redis 캐시 → DB UNIQUE → race 시 첫 결과 재조회). 두 wallet에 대한 분산 락(wallet_id 오름차순 MultiLock) + DB 비관적 락으로 동시성 보호. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    post: operations['executeTransfer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/scheduled': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 정기 송금 목록 조회
     * @description 로그인한 회원 본인이 설정한 정기 송금 목록을 페이지 단위로 조회한다. status 쿼리 파라미터로 ACTIVE/PAUSED/CANCELLED 필터링 가능 (미지정 시 전체). 정렬은 created_at DESC(최신 설정 우선). 잘못된 status 값은 COMMON4001.
     */
    get: operations['list'];
    put?: never;
    /**
     * 정기 송금 설정
     * @description 매주/매월 자동 실행되는 정기 송금을 설정한다. 설정 즉시 ACTIVE 상태로 등록되며 다음 실행 예정일(next_run_date)이 KST 기준으로 계산된다. 송금 실행 API와 동일하게 transfer_type으로 INTERNAL_TRANSFER/REMITTANCE 분기.
     */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/scheduled/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 정기 송금 대상 유효성 검증
     * @description 정기 송금 설정 전 (수취 대상, 금액, 통화) 조합이 유효한지 사전 검증한다. 도메인 검증(통화 정합성 등) 미통과는 200 + is_valid=false + reason으로 응답되며, 입력 형식·계좌 미존재·미인증·자기송금 등은 도메인 에러(400/403/404)로 응답된다. 송금 실행 API와 동일하게 transfer_type으로 INTERNAL_TRANSFER/REMITTANCE 분기.
     */
    post: operations['validateScheduled'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/pin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 송금 PIN 설정
     * @description 송금 시 본인확인용 PIN(숫자 6자리)을 최초 설정한다. 이미 설정돼 있으면 COMMON4091. PIN 변경(기존 PIN 확인 후 교체)은 후속 기능.
     */
    post: operations['setPin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/pin-verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 송금 PIN 검증
     * @description 송금 실행 전 PIN을 검증한다. 성공 시 송금 생성 API로 진행한다. 5회 연속 실패 시 10분간 잠긴다.
     */
    post: operations['verifyPin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/fee': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 송금 수수료 조회
     * @description 송금 화면에서 입력한 방식·통화·금액으로 수수료를 계산해 반환한다. 정책(docs/remittance/api-spec.md §4): INTERNAL_TRANSFER=0, REMITTANCE=amount×0.5%(HALF_UP 4자리). DB·외부 호출 없는 순수 계산. 미지원 통화(KRW/USD/PHP/VND 외)는 TRANSFER4002. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    post: operations['getTransferFee'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exchanges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * (재)환전 내역 목록 조회
     * @description 본인의 환전·재환전 완료 내역을 최근순으로 페이지 조회한다. data.exchanges 배열 + 페이지 메타(page/size/total_elements/total_pages).
     */
    get: operations['getExchanges'];
    put?: never;
    /**
     * (재)환전 실행
     * @description 견적 식별자(quote_public_id)로 환전을 실행하고 지갑 잔액을 갱신한다. Idempotency-Key 헤더로 멱등성을 보장한다(동일 키 재요청 시 첫 결과 재반환).
     */
    post: operations['execute'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exchanges/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 실시간 (재)환전 견적 조회 및 검증
     * @description 환전/재환전의 실시간 환율과 예상 수령액을 계산해 견적을 발급한다(5분간 유효). 발급된 quote_public_id로 환전을 실행한다.
     */
    post: operations['createQuote'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 등록된 내 계좌 목록 조회
     * @description 요청 회원이 등록한 활성 은행 계좌를 주 계좌 우선, 최신 등록순으로 반환한다. 계좌번호는 마스킹되어(앞 3 + 끝 2) 전달된다. 등록된 계좌가 없으면 404가 아닌 200 + accounts: [] 빈 배열로 응답한다. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    get: operations['getMyAccounts'];
    put?: never;
    /**
     * 계좌 등록 최종 완료
     * @description verify에서 발급받은 account_token과 계좌 정보를 받아 bank_accounts에 INSERT한다. 사용자의 첫 등록 계좌는 자동으로 주 계좌(is_primary=true)로 설정된다.
     */
    post: operations['registerAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/{id}/charge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 충전 금액 검증·실행
     * @description 등록된 계좌의 mock_account_token으로 Mock 은행에 출금을 요청해 본체 KRW 잔액을 증액한다. 동일 Idempotency-Key 재요청 시 첫 응답을 부수효과 없이 재반환한다(멱등성).
     */
    post: operations['charge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 계좌 연결 + 자동이체 인증 요청
     * @description 은행 코드/계좌번호/예금주명으로 외부 Mock 은행에 자동이체 인증을 요청해 account_token을 발급받는다. 본체 DB에는 아무것도 쓰지 않으며, 이어지는 POST /accounts 호출 시 클라이언트가 이 토큰을 함께 보내야 한다. 자동이체 인증은 Mock 은행 시뮬레이션으로 처리된다(실 은행 연동 전).
     */
    post: operations['verifyAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/{id}/primary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 주 계좌 변경
     * @description 요청 회원의 활성 계좌 중 하나를 주 계좌로 지정한다. 기존 주 계좌는 자동으로 해제되어 사용자당 주 계좌가 항상 1개로 유지된다. 이미 주 계좌인 계좌를 다시 지정하면 멱등 성공(200)이다. data에 변경된 AccountResponse(is_primary=true)가 담긴다.
     */
    patch: operations['changePrimary'];
    trace?: never;
  };
  '/api/v1/wallets/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 전자지갑 원화 환산 조회
     * @description 인증된 사용자의 전자지갑 상태 + 통화별 잔액 + 원화 환산 + 전체 합산 원화 평가액을 조회한다. 각 통화는 ExchangeRateClient("1 외화→KRW")로 환율을 받아 잔액에 곱한다. 환율 소스: dev=고정 환율표(Mock) / stage·prod=Redis(rate:KRW-<통화>, exchange-updater cron이 매일 자정 갱신). 미지원 통화 발생 시 TRANSFER4002. JWT public_id claim으로 사용자 식별.
     */
    get: operations['getMyWallet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/wallets/me/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 전자지갑 거래내역 조회
     * @description 본인의 모든 유형(CHARGE/INTERNAL_TRANSFER/REMITTANCE/EXCHANGE) 거래를 최근순으로 페이지 조회한다. data.transactions 배열 + 페이지 메타(page/size/total_elements/total_pages). 거래가 없으면 200 + 빈 배열로 응답한다. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    get: operations['getMyTransactions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/wallets/me/balances': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 전자지갑 잔액 조회
     * @description 인증된 사용자의 전자지갑과 통화별 잔액 목록을 조회한다. 잔액은 명세에 따라 소수점 4자리 string으로 응답한다. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    get: operations['getMyBalances'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/wallets/exchange-rates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 주요 통화 환율 위젯 조회
     * @description 기준 통화 KRW 대비 주요 통화의 "1 외화→KRW" 환율과 전일 대비 등락률(%)을 조회한다. currency_codes(콤마 구분)로 통화를 선별하며, 생략 시 KRW를 제외한 전체 지원 통화를 반환한다. 환율 소스: dev=고정 환율표(Mock) / stage·prod=Redis(rate:KRW-<통화>, exchange-updater cron 매일 자정 갱신). 등락률은 직전 값(rate:KRW-<통화>:prev)과 비교해 산정하며 직전 값이 없으면 0. 미지원 통화 코드 입력 시 TRANSFER4002.
     */
    get: operations['getExchangeRates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/{transferPublicId}/receipt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 송금 확인증 조회
     * @description 완료된 송금 한 건의 확인증(송·수취인, 금액, 수수료, 적용 환율, 수취 금액 등)을 조회한다. 대상은 INTERNAL_TRANSFER · REMITTANCE만이며, 송신자 본인만 조회 가능하다. 본인 아님·미존재·미지원 유형은 정보 누설 방지로 동일한 TRANSFER4001로 모호 매핑한다.
     */
    get: operations['getReceipt'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/validate-member': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 앱 사용자 유효성 검증
     * @description 송금 화면에서 수취인 이메일로 앱 사용자가 존재하는지 검증한다. 존재하면 receiver_public_id/nickname/is_verified를 반환, 없으면 404 MEMBER4001. 이 API는 본인 식별보다 '대상 회원 검증'이 핵심이지만 인증은 필요하다.
     */
    get: operations['validateMember'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/supported-currencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지원 통화 목록 조회
     * @description 송금/환전 화면에서 사용 가능한 통화 4종(KRW/USD/PHP/VND)을 반환한다. CurrencyType enum이 SSOT라 DB/외부 호출 없는 순수 enum 조회. 이 API는 본인 식별이 비즈니스에 영향이 없지만 인증은 필요하다.
     */
    get: operations['getSupportedCurrencies'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/scheduled/{transferPublicId}/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 정기 송금 회차 실행 이력 조회
     * @description 특정 정기 송금의 회차별 실행 이력(transactions)을 페이지 단위로 조회한다. 회차 거래는 스케줄러가 idempotency_key='scheduled:{publicId}:{nextRunDate}' 형태로 INSERT한 행. 송신자 본인만 조회 가능하며, 미존재·본인 아님 모두 TRANSFER4001로 모호 매핑(정보 누설 방지). 현 단계는 status가 항상 COMPLETED — 송금 실패 시 transactions INSERT 자체 안 됨.
     */
    get: operations['getHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/recent-recipients/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 최근 송금 앱 사용자 조회
     * @description 내가 송신자였던 앱 내부 송금(INTERNAL_TRANSFER, COMPLETED) 기록에서 수신자별 가장 최근 송금 1건씩, 최근순으로 최대 10명을 반환한다. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    get: operations['getRecentInternalRecipients'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/transfers/recent-accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 최근 송금 계좌 조회
     * @description 내가 송신자였던 타행 송금(REMITTANCE, COMPLETED) 기록에서 bank_account별 가장 최근 송금 1건씩, 최근순으로 size건(기본 10, 1~50)을 반환한다. wallet 도메인 내부 DB만 조회하며 외부 호출 없음. 사용자는 JWT의 public_id claim으로 식별한다.
     */
    get: operations['getRecentRemittanceAccounts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exchanges/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * (재)환전 완료 내역 조회
     * @description 환전 내역 식별자(public_id)로 특정 환전 완료 내역의 상세를 조회한다(본인 것만).
     */
    get: operations['getExchange'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exchanges/supported-currencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지원 (재)환전 통화 목록 조회
     * @description 환전·재환전에서 사용 가능한 지원 통화 목록을 조회한다. (통화 코드/이름/기호)
     */
    get: operations['getSupportedCurrencies_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/supported-banks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 추가 지원 은행 목록 조회
     * @description 충전·현금화 계좌 등록 시 선택 가능한 활성 국내 은행 목록을 가나다순으로 반환한다. Beaver/Quokka Bank 등 시뮬레이션 은행도 활성 상태이면 포함된다. 마스터 데이터 조회라 결과는 사용자와 무관하지만 인증은 필요하다.
     */
    get: operations['getSupportedBanks'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/holder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 예금주 실명 조회
     * @description 은행 코드와 계좌번호로 외부 Mock 은행(Beaver/Quokka Bank)에 조회해 예금주 실명을 가져온다. 계좌 등록(/accounts/verify)을 시작하기 전에 사용자가 입력한 계좌번호의 예금주를 보여주는 용도다. 본체 DB에는 아무것도 쓰지 않는다.
     */
    get: operations['getAccountHolder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/accounts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 계좌 삭제
     * @description 지정한 계좌를 삭제(soft-delete, is_active=false)한다. 주 계좌를 삭제하면 남은 활성 계좌 중 가장 최근 등록 1건이 자동으로 주 계좌로 승격된다(마지막 1개면 주 계좌 없는 상태 허용). 성공 시 200 + data:null.
     */
    delete: operations['deleteAccount'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description 송금 실행 요청 (1단계: INTERNAL_TRANSFER + 같은 통화 전용)
     * @example {
     *       "transfer_type": "INTERNAL_TRANSFER",
     *       "amount": "10000.0000",
     *       "currency_code": "KRW",
     *       "receive_currency_code": "KRW",
     *       "memo": "생활비",
     *       "receiver_public_id": "11111111-1111-1111-1111-111111111111"
     *     }
     */
    TransferExecuteRequest: {
      /**
       * @description 송금 방식 (1단계는 INTERNAL_TRANSFER만 허용)
       * @example INTERNAL_TRANSFER
       * @enum {string}
       */
      transferType: 'INTERNAL_TRANSFER' | 'REMITTANCE';
      /**
       * @description 송금 금액 (string 십진수, 소수점 최대 4자리, 양수)
       * @example 10000
       */
      amount: string;
      /**
       * @description 송금 통화 코드
       * @example KRW
       */
      currencyCode: string;
      /**
       * @description 수취 통화 코드 (1단계는 currency_code와 같아야 함, 다르면 TRANSFER4005)
       * @example KRW
       */
      receiveCurrencyCode: string;
      /**
       * @description 메모(선택, 최대 255자)
       * @example 생활비
       */
      memo?: string;
      /**
       * @description 수신자 회원 식별자(UUID, INTERNAL_TRANSFER 필수)
       * @example 11111111-1111-1111-1111-111111111111
       */
      receiverPublicId: string;
      /**
       * @description 수신 은행 계좌 식별자(REMITTANCE 전용, 1단계 미사용)
       * @example null
       */
      bankAccountPublicId?: string;
    };
    /** @description 공통 실패 응답. 성공 응답과 달리 data 키가 없고 비즈니스 code가 포함된다. */
    ErrorResponse: {
      /**
       * @description 성공 여부. 실패 응답에선 항상 false.
       * @example false
       */
      success?: boolean;
      /**
       * @description 비즈니스 에러 코드({DOMAIN}{4자리}).
       * @example WALLET4001
       */
      code?: string;
      /**
       * @description 사용자에게 보여줄 에러 메시지.
       * @example 존재하지 않는 지갑입니다.
       */
      message?: string;
    };
    ApiResponseTransferExecuteResponse: {
      success?: boolean;
      data?: components['schemas']['TransferExecuteResponse'];
      message?: string;
    };
    /** @description 송금 실행 결과 */
    TransferExecuteResponse: {
      /**
       * @description 거래 식별자(UUID, public_id)
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      publicId?: string;
      /**
       * @description 송금 방식
       * @example INTERNAL_TRANSFER
       * @enum {string}
       */
      transferType?: 'INTERNAL_TRANSFER' | 'REMITTANCE';
      /**
       * @description 송금 금액 (string 십진수, 소수점 4자리)
       * @example 10000
       */
      amount?: string;
      /**
       * @description 송금 통화 코드
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 송금 수수료 (string 십진수, 소수점 4자리)
       * @example 0
       */
      fee?: string;
      /**
       * @description 적용 환율 (1단계 같은 통화는 항상 null)
       * @example null
       */
      exchangeRate?: string;
      /**
       * @description 수취 금액 (1단계는 amount와 동일, string 십진수)
       * @example 10000
       */
      receiveAmount?: string;
      /**
       * @description 수취 통화 코드
       * @example KRW
       */
      receiveCurrencyCode?: string;
      /**
       * @description 거래 상태
       * @example COMPLETED
       */
      status?: string;
      /**
       * @description 거래 생성 시각(ISO 8601, UTC Z)
       * @example 2026-06-01T03:15:30Z
       */
      createdAt?: string;
    };
    /**
     * @description 정기 송금 설정 요청
     * @example {
     *       "transfer_type": "REMITTANCE",
     *       "bank_account_public_id": "7g8h9i0j-1234-5678-90ab-cdef12345678",
     *       "amount": "500000.0000",
     *       "currency_code": "KRW",
     *       "receive_currency_code": "KRW",
     *       "frequency": "MONTHLY",
     *       "schedule_day": 25,
     *       "memo": "매달 생활비"
     *     }
     */
    CreateScheduledTransferRequest: {
      /**
       * @description 송금 방식
       * @example REMITTANCE
       * @enum {string}
       */
      transferType: 'INTERNAL_TRANSFER' | 'REMITTANCE';
      /**
       * @description 수신자 회원 식별자(UUID, INTERNAL_TRANSFER 필수)
       * @example 11111111-1111-1111-1111-111111111111
       */
      receiverPublicId?: string;
      /**
       * @description 수신 은행 계좌 식별자(UUID, REMITTANCE 필수)
       * @example 7g8h9i0j-1234-5678-90ab-cdef12345678
       */
      bankAccountPublicId?: string;
      /**
       * @description 회차당 송금액 (string 십진수, 소수점 최대 4자리, 양수)
       * @example 500000
       */
      amount: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      currencyCode: string;
      /**
       * @description 수취 통화 코드 (1·2단계 same-currency 강제, 다르면 COMMON4221)
       * @example KRW
       */
      receiveCurrencyCode: string;
      /**
       * @description 반복 주기
       * @example MONTHLY
       * @enum {string}
       */
      frequency: 'WEEKLY' | 'MONTHLY';
      /**
       * Format: int32
       * @description 실행 기준일 (MONTHLY=1~31, WEEKLY=1~7 ISO 요일/1=월). 범위 초과 시 COMMON4221.
       * @example 25
       */
      scheduleDay: number;
      /**
       * @description 메모(선택, 최대 255자)
       * @example 매달 생활비
       */
      memo?: string;
    };
    ApiResponseScheduledTransferResponse: {
      success?: boolean;
      data?: components['schemas']['ScheduledTransferResponse'];
      message?: string;
    };
    /** @description 정기 송금 설정 결과 */
    ScheduledTransferResponse: {
      /**
       * @description 정기 송금 식별자(UUID)
       * @example 2b3c4d5e-1234-5678-90ab-cdef12345678
       */
      publicId?: string;
      /**
       * @description 송금 방식
       * @example REMITTANCE
       * @enum {string}
       */
      transferType?: 'INTERNAL_TRANSFER' | 'REMITTANCE';
      /**
       * @description 회차당 송금액 (string 십진수)
       * @example 500000
       */
      amount?: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 수취 통화 코드
       * @example KRW
       */
      receiveCurrencyCode?: string;
      /**
       * @description 반복 주기
       * @example MONTHLY
       * @enum {string}
       */
      frequency?: 'WEEKLY' | 'MONTHLY';
      /**
       * Format: int32
       * @description 실행 기준일 (MONTHLY=1~31, WEEKLY=1~7 ISO)
       * @example 25
       */
      scheduleDay?: number;
      /**
       * @description 다음 실행 예정일 (ISO 8601 date, KST 기준)
       * @example 2026-06-25
       */
      nextRunDate?: string;
      /**
       * @description 마지막 실행 시각 (ISO 8601 UTC Z). 최초 실행 전이면 null
       * @example 2026-05-25T16:00:00Z
       */
      lastRunAt?: string;
      /**
       * @description 상태
       * @example ACTIVE
       * @enum {string}
       */
      status?: 'ACTIVE' | 'PAUSED' | 'CANCELLED';
      /**
       * @description 생성 시각 (ISO 8601 UTC Z)
       * @example 2026-05-25T13:00:00Z
       */
      createdAt?: string;
    };
    /**
     * @description 정기 송금 대상 유효성 검증 요청
     * @example {
     *       "transfer_type": "REMITTANCE",
     *       "bank_account_public_id": "7g8h9i0j-1234-5678-90ab-cdef12345678",
     *       "amount": "500000.0000",
     *       "currency_code": "KRW",
     *       "receive_currency_code": "KRW"
     *     }
     */
    ValidateScheduledRequest: {
      /**
       * @description 송금 방식
       * @example REMITTANCE
       * @enum {string}
       */
      transferType: 'INTERNAL_TRANSFER' | 'REMITTANCE';
      /**
       * @description 수신자 회원 식별자(UUID, INTERNAL_TRANSFER 필수)
       * @example 11111111-1111-1111-1111-111111111111
       */
      receiverPublicId?: string;
      /**
       * @description 수신 은행 계좌 식별자(UUID, REMITTANCE 필수)
       * @example 7g8h9i0j-1234-5678-90ab-cdef12345678
       */
      bankAccountPublicId?: string;
      /**
       * @description 회차당 송금액 (string 십진수, 소수점 최대 4자리, 양수)
       * @example 500000
       */
      amount: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      currencyCode: string;
      /**
       * @description 수취 통화 코드 (1·2단계 same-currency 강제 — 다르면 is_valid=false + reason)
       * @example KRW
       */
      receiveCurrencyCode: string;
    };
    ApiResponseValidateScheduledResponse: {
      success?: boolean;
      data?: components['schemas']['ValidateScheduledResponse'];
      message?: string;
    };
    /** @description 정기 송금 대상 검증 결과 */
    ValidateScheduledResponse: {
      /**
       * @description 검증 통과 여부
       * @example true
       */
      isValid?: boolean;
      /**
       * @description 미통과 사유. is_valid=true면 null
       * @example null
       */
      reason?: string;
    };
    TransferPinRequest: {
      /**
       * @description 송금 PIN (숫자 6자리)
       * @example 123456
       */
      pin: string;
    };
    ApiResponseVoid: {
      success?: boolean;
      data?: unknown;
      message?: string;
    };
    /**
     * @description 송금 수수료 조회 요청
     * @example {
     *       "transfer_type": "REMITTANCE",
     *       "currency_code": "KRW",
     *       "amount": "10000.0000"
     *     }
     */
    TransferFeeRequest: {
      /**
       * @description 송금 방식
       * @example REMITTANCE
       * @enum {string}
       */
      transferType: 'INTERNAL_TRANSFER' | 'REMITTANCE';
      /**
       * @description 송금 통화 코드
       * @example KRW
       */
      currencyCode: string;
      /**
       * @description 송금 금액 (string 십진수, 소수점 최대 4자리, 양수)
       * @example 10000
       */
      amount: string;
    };
    ApiResponseTransferFeeResponse: {
      success?: boolean;
      data?: components['schemas']['TransferFeeResponse'];
      message?: string;
    };
    TransferFeeResponse: {
      /**
       * @description 송금 수수료 (string 십진수, 소수점 4자리)
       * @example 50
       */
      fee?: string;
      /**
       * @description 수수료 통화 코드 (송금 통화와 동일)
       * @example KRW
       * @enum {string}
       */
      feeCurrencyCode?: 'KRW' | 'USD' | 'PHP' | 'VND';
      /**
       * @description 총 출금 금액(amount + fee, string 십진수, 소수점 4자리)
       * @example 10050
       */
      totalDeductAmount?: string;
    };
    ExchangeExecuteRequest: {
      /**
       * @description 견적 조회에서 발급받은 견적 식별자(UUID)
       * @example 9f8e7d6c-1234-5678-abcd-ef0123456789
       */
      quotePublicId: string;
    };
    ApiResponseExchangeResponse: {
      success?: boolean;
      data?: components['schemas']['ExchangeResponse'];
      message?: string;
    };
    ExchangeResponse: {
      public_id?: string;
      exchange_type?: string;
      from_currency_code?: string;
      to_currency_code?: string;
      /**
       * @description 환전 신청 금액 (string)
       * @example 100000
       */
      amount?: string;
      exchange_rate?: string;
      /**
       * @description 수수료 (string, KRW 기준)
       * @example 1000
       */
      fee?: string;
      receive_amount?: string;
      receive_currency_code?: string;
      /**
       * @description 거래 상태
       * @example COMPLETED
       */
      status?: string;
      exchanged_at?: string;
      /**
       * @description 환전 내역 식별자(UUID)
       * @example 1a2b3c4d-5678-90ab-cdef-012345678901
       */
      publicId?: string;
      /**
       * @description 환전 유형 (EXCHANGE / RE_EXCHANGE)
       * @example EXCHANGE
       */
      exchangeType?: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      fromCurrencyCode?: string;
      /**
       * @description 입금 통화 코드
       * @example USD
       */
      toCurrencyCode?: string;
      /**
       * @description 적용 환율 (string, "1 외화→KRW")
       * @example 1380
       */
      exchangeRate?: string;
      /**
       * @description 실제 수령액 (string)
       * @example 72.45
       */
      receiveAmount?: string;
      /**
       * @description 수령 통화 코드
       * @example USD
       */
      receiveCurrencyCode?: string;
      /**
       * @description 환전 완료 시각 (ISO 8601 UTC Z)
       * @example 2026-05-26T05:30:00Z
       */
      exchangedAt?: string;
    };
    QuoteRequest: {
      /**
       * @description 환전 유형 (EXCHANGE: 원화→외화 / RE_EXCHANGE: 외화→원화)
       * @example EXCHANGE
       */
      exchangeType: string;
      /**
       * @description 출금 통화 코드 (ISO 4217)
       * @example KRW
       */
      fromCurrencyCode: string;
      /**
       * @description 입금 통화 코드 (ISO 4217)
       * @example USD
       */
      toCurrencyCode: string;
      /**
       * @description 환전 신청 금액 (string 십진수, 소수점 최대 4자리, 양수)
       * @example 100000
       */
      amount: string;
    };
    ApiResponseQuoteResponse: {
      success?: boolean;
      data?: components['schemas']['QuoteResponse'];
      message?: string;
    };
    QuoteResponse: {
      /**
       * @description 견적 식별자(UUID, 환전 실행 시 사용)
       * @example 9f8e7d6c-1234-5678-abcd-ef0123456789
       */
      quotePublicId?: string;
      /**
       * @description 적용 환율 (string, "1 외화→KRW")
       * @example 1380
       */
      exchangeRate?: string;
      /**
       * @description 수수료 (string, KRW 기준)
       * @example 1000
       */
      fee?: string;
      /**
       * @description 수수료 통화 코드
       * @example KRW
       */
      feeCurrencyCode?: string;
      /**
       * @description 예상 수령액 (string)
       * @example 72.45
       */
      receiveAmount?: string;
      /**
       * @description 수령 통화 코드 (ISO 4217)
       * @example USD
       */
      receiveCurrencyCode?: string;
      /**
       * @description 견적 만료 시각 (ISO 8601 UTC Z)
       * @example 2026-05-26T05:35:00Z
       */
      expiresAt?: string;
    };
    RegisterAccountRequest: {
      /**
       * @description 은행 코드
       * @example 004
       */
      bankCode: string;
      /**
       * @description 계좌번호(하이픈 없는 숫자 문자열)
       * @example 1234567890
       */
      accountNumber: string;
      /**
       * @description verify 단계에서 발급받은 외부(Mock) 은행 토큰
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      accountToken: string;
      /**
       * @description 예금주명. GET /accounts/holder 응답의 account_holder_name을 그대로 전달
       * @example NGUYEN VAN A
       */
      holderName: string;
    };
    AccountResponse: {
      /**
       * @description 계좌 식별자(UUID)
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      accountPublicId?: string;
      /**
       * @description 은행 코드
       * @example 004
       */
      bankCode?: string;
      /**
       * @description 은행명
       * @example KB국민은행
       */
      bankName?: string;
      /**
       * @description 마스킹된 계좌번호 (앞 3자리 + 끝 2자리 노출)
       * @example 123*********34
       */
      accountNumberMasked?: string;
      /**
       * @description 주 계좌 여부
       * @example true
       */
      isPrimary?: boolean;
      /**
       * @description 가상계좌(앱 내부 발급) 여부
       * @example false
       */
      isVirtual?: boolean;
      /**
       * @description 외부 은행 인증 완료 여부 (mock_account_token 존재 && is_active)
       * @example true
       */
      isVerified?: boolean;
      /**
       * @description 계좌 등록 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      createdAt?: string;
    };
    ApiResponseAccountResponse: {
      success?: boolean;
      data?: components['schemas']['AccountResponse'];
      message?: string;
    };
    ChargeRequest: {
      /**
       * @description 충전 금액(string 십진수, KRW). 0 초과.
       * @example 1530000
       */
      amount: number;
    };
    ApiResponseChargeResponse: {
      success?: boolean;
      data?: components['schemas']['ChargeResponse'];
      message?: string;
    };
    ChargeResponse: {
      public_id?: string;
      account_public_id?: string;
      /**
       * @description 충전 금액(string, 소수 4자리)
       * @example 1530000
       */
      amount?: string;
      currency_code?: string;
      wallet_balance?: string;
      /**
       * @description 거래 상태
       * @example COMPLETED
       */
      status?: string;
      created_at?: string;
      /**
       * @description 충전 거래 식별자(UUID)
       * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
       */
      publicId?: string;
      /**
       * @description 출금 계좌 식별자(UUID, 요청 path의 id와 동일)
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      accountPublicId?: string;
      /**
       * @description 통화 코드(KRW 고정)
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 충전 후 지갑 잔액(string, 소수 4자리)
       * @example 5430000
       */
      walletBalance?: string;
      /**
       * @description 거래 생성 시각(ISO 8601, UTC Z)
       * @example 2026-05-30T04:15:30Z
       */
      createdAt?: string;
    };
    VerifyAccountRequest: {
      /**
       * @description 은행 코드
       * @example 004
       */
      bankCode: string;
      /**
       * @description 계좌번호(하이픈 없는 숫자 문자열)
       * @example 1234567890
       */
      accountNumber: string;
      /**
       * @description 예금주명
       * @example 홍길동
       */
      holderName: string;
    };
    ApiResponseVerifyAccountResponse: {
      success?: boolean;
      data?: components['schemas']['VerifyAccountResponse'];
      message?: string;
    };
    VerifyAccountResponse: {
      /**
       * @description 외부(Mock) 은행이 발급한 계좌 토큰. 계좌 등록 시 본문에 함께 전달한다.
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      accountToken?: string;
    };
    ApiResponseWalletMeResponse: {
      success?: boolean;
      data?: components['schemas']['WalletMeResponse'];
      message?: string;
    };
    BalanceWithKrwItem: {
      /**
       * @description 통화 코드
       * @example KRW
       * @enum {string}
       */
      currencyCode?: 'KRW' | 'USD' | 'PHP' | 'VND';
      /**
       * @description 해당 통화 잔액 (소수점 4자리 string)
       * @example 1530000
       */
      balance?: string;
      /**
       * @description 적용 환율 ("1 외화→KRW" 고정, string 십진수). KRW 는 "1"
       * @example 1380
       */
      exchangeRate?: string;
      /**
       * @description 해당 통화 잔액의 원화 환산액
       * @example 345000
       */
      balanceInKrw?: string;
    };
    WalletMeResponse: {
      /**
       * @description 전자지갑 식별자(UUID)
       * @example a1b2c3d4-1111-2222-3333-444455556666
       */
      walletPublicId?: string;
      /**
       * @description 지갑 상태
       * @example ACTIVE
       * @enum {string}
       */
      status?: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
      /**
       * @description 전체 보유 통화의 원화 환산 합계 (string 십진수)
       * @example 1888500
       */
      totalBalanceInKrw?: string;
      /** @description 통화별 잔액 및 원화 환산 목록 */
      balances?: components['schemas']['BalanceWithKrwItem'][];
      /**
       * @description 잔액·환산 기준 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      updatedAt?: string;
    };
    ApiResponseTransactionListResponse: {
      success?: boolean;
      data?: components['schemas']['TransactionListResponse'];
      message?: string;
    };
    TransactionHistoryItemResponse: {
      /**
       * @description 거래 식별자(UUID)
       * @example 1a2b3c4d-5678-90ab-cdef-012345678901
       */
      publicId?: string;
      /**
       * @description 거래 유형
       * @example CHARGE
       * @enum {string}
       */
      type?: 'CHARGE' | 'INTERNAL_TRANSFER' | 'REMITTANCE' | 'EXCHANGE';
      /**
       * @description 거래 상태
       * @example COMPLETED
       * @enum {string}
       */
      status?: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';
      /**
       * @description 거래(출금) 금액 (string, 소수 4자리)
       * @example 500000
       */
      amount?: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 수수료 (string, 소수 4자리)
       * @example 0
       */
      fee?: string;
      /**
       * @description 수령액 (string, 환전·송금만, nullable)
       * @example 72.45
       */
      receiveAmount?: string;
      /**
       * @description 수령 통화 코드 (환전·송금만, nullable)
       * @example USD
       */
      receiveCurrencyCode?: string;
      /**
       * @description 수취인 이름 (송금만, nullable)
       * @example 홍길동
       */
      receiverName?: string;
      /**
       * @description 거래 시각 (ISO 8601 UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      createdAt?: string;
    };
    TransactionListResponse: {
      /** @description 거래내역 목록(최근순) */
      transactions?: components['schemas']['TransactionHistoryItemResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지(0부터)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지당 건수
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 건수
       * @example 42
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 3
       */
      totalPages?: number;
    };
    ApiResponseWalletBalanceResponse: {
      success?: boolean;
      data?: components['schemas']['WalletBalanceResponse'];
      message?: string;
    };
    BalanceItem: {
      /**
       * @description 통화 코드
       * @example KRW
       * @enum {string}
       */
      currencyCode?: 'KRW' | 'USD' | 'PHP' | 'VND';
      /**
       * @description 잔액(소수점 4자리 고정 string)
       * @example 1530000
       */
      balance?: string;
    };
    WalletBalanceResponse: {
      /**
       * @description 전자지갑 식별자(UUID)
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      walletPublicId?: string;
      /**
       * @description 지갑 상태
       * @example ACTIVE
       * @enum {string}
       */
      status?: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
      /** @description 통화별 잔액 목록 */
      balances?: components['schemas']['BalanceItem'][];
      /**
       * @description 잔액 최종 변경 시각(ISO 8601, UTC Z)
       * @example 2026-05-26T04:15:30Z
       */
      updatedAt?: string;
    };
    ApiResponseExchangeRateWidgetResponse: {
      success?: boolean;
      data?: components['schemas']['ExchangeRateWidgetResponse'];
      message?: string;
    };
    ExchangeRateWidgetResponse: {
      /**
       * @description 기준 통화 코드. 항상 KRW ("1 외화→KRW" 환산 기준)
       * @example KRW
       */
      baseCurrencyCode?: string;
      /** @description 통화별 환율 목록 */
      rates?: components['schemas']['RateItem'][];
    };
    RateItem: {
      /**
       * @description 통화 코드 (ISO 4217)
       * @example USD
       */
      currencyCode?: string;
      /**
       * @description 통화명(한국어)
       * @example 미국 달러
       */
      currencyName?: string;
      /**
       * @description 통화 기호
       * @example $
       */
      currencySymbol?: string;
      /**
       * @description 환율 ("1 외화→KRW", string 십진수)
       * @example 1380.5
       */
      exchangeRate?: string;
      /**
       * @description 전일 대비 등락률(%). 표시 전용 number. 직전 값 없으면 0
       * @example 0.32
       */
      changeRate?: number;
      /**
       * @description 환율 조회 기준 시각 (ISO 8601, UTC Z)
       * @example 2026-05-26T04:00:00Z
       */
      updatedAt?: string;
    };
    ApiResponseTransferReceiptResponse: {
      success?: boolean;
      data?: components['schemas']['TransferReceiptResponse'];
      message?: string;
    };
    /** @description 송금 확인증 */
    TransferReceiptResponse: {
      /**
       * @description 거래 식별자(UUID, public_id)
       * @example 9b2e4c1a-7f3d-4b8e-9a1c-2d5e6f7a8b9c
       */
      publicId?: string;
      /**
       * @description 송금인 본명(name, 요청자 본인). 본인 확인증이므로 호출 시점 user_public_id로 풀어 표시할 수도 있으나, 송금 당시 정보 보존을 위해 거래 시점 snapshot 가능. 현재 구현은 호출 시 sender 본명(name) fetch.
       * @example Linh
       */
      senderName?: string;
      /**
       * @description 수취인명. INTERNAL은 수신자 본명(name), REMITTANCE는 등록 시 저장된 예금주명(holder_name, GET /accounts/holder 응답 출처). 외부 장애·구 계좌 등으로 null 가능
       * @example NGUYEN VAN A
       */
      receiverName?: string;
      /**
       * @description 수취 은행명. REMITTANCE만 값 있음, INTERNAL은 null
       * @example Quokka Bank
       */
      bankName?: string;
      /**
       * @description 수취 계좌번호(마스킹). REMITTANCE만 값 있음, INTERNAL은 null
       * @example ****1234
       */
      accountNumber?: string;
      /**
       * @description 송금 금액 (string 십진수, 소수점 4자리)
       * @example 500000
       */
      amount?: string;
      /**
       * @description 송금 통화 코드
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 송금 수수료 (string 십진수, 소수점 4자리)
       * @example 3000
       */
      fee?: string;
      /**
       * @description 적용 환율 (1·2단계 same-currency는 항상 null, 3단계 다통화부터 값)
       * @example 18.025
       */
      exchangeRate?: string;
      /**
       * @description 수취 금액 (1·2단계는 amount와 동일, string 십진수)
       * @example 500000
       */
      receiveAmount?: string;
      /**
       * @description 수취 통화 코드
       * @example KRW
       */
      receiveCurrencyCode?: string;
      /**
       * @description 거래 상태
       * @example COMPLETED
       */
      status?: string;
      /**
       * @description 송금 시각(ISO 8601, UTC Z)
       * @example 2026-05-25T12:00:00Z
       */
      createdAt?: string;
    };
    ApiResponseValidateMemberResponse: {
      success?: boolean;
      data?: components['schemas']['ValidateMemberResponse'];
      message?: string;
    };
    ValidateMemberResponse: {
      /**
       * @description 수신자 회원 식별자(UUID)
       * @example 11111111-1111-1111-1111-111111111111
       */
      receiverPublicId?: string;
      /**
       * @description 수신자 닉네임
       * @example Linh
       */
      nickname?: string;
      verified?: boolean;
      /**
       * @description 회원 인증 배지 여부
       * @example true
       */
      is_verified?: boolean;
    };
    ApiResponseSupportedCurrenciesResponse: {
      success?: boolean;
      data?: components['schemas']['SupportedCurrenciesResponse'];
      message?: string;
    };
    CurrencyItem: {
      /**
       * @description 통화 코드(ISO 4217)
       * @example KRW
       * @enum {string}
       */
      code?: 'KRW' | 'USD' | 'PHP' | 'VND';
      /**
       * @description 통화 영문 명칭
       * @example Korean Won
       */
      name?: string;
      /**
       * @description 통화 기호
       * @example ₩
       */
      symbol?: string;
    };
    SupportedCurrenciesResponse: {
      /** @description 지원 통화 목록 (CurrencyType enum SSOT 기반) */
      currencies?: components['schemas']['CurrencyItem'][];
    };
    ApiResponseScheduledTransferListResponse: {
      success?: boolean;
      data?: components['schemas']['ScheduledTransferListResponse'];
      message?: string;
    };
    /** @description 정기 송금 목록 항목 */
    ScheduledTransferListItem: {
      /**
       * @description 정기 송금 식별자(UUID)
       * @example 2b3c4d5e-1234-5678-90ab-cdef12345678
       */
      publicId?: string;
      /**
       * @description 수취인명 (설정 시 snapshot)
       * @example NGUYEN VAN A
       */
      receiverName?: string;
      /**
       * @description 회차당 송금액 (string 십진수)
       * @example 500000
       */
      amount?: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 수취 통화 코드
       * @example KRW
       */
      receiveCurrencyCode?: string;
      /**
       * @description 반복 주기
       * @example MONTHLY
       * @enum {string}
       */
      frequency?: 'WEEKLY' | 'MONTHLY';
      /**
       * Format: int32
       * @description 실행 기준일 (MONTHLY=1~31, WEEKLY=1~7 ISO)
       * @example 25
       */
      scheduleDay?: number;
      /**
       * @description 다음 실행 예정일 (ISO 8601 date, KST 기준)
       * @example 2026-06-25
       */
      nextRunDate?: string;
      /**
       * @description 마지막 실행 시각 (ISO 8601 UTC Z). 최초 실행 전이면 null
       * @example 2026-05-25T16:00:00Z
       */
      lastRunAt?: string;
      /**
       * @description 상태
       * @example ACTIVE
       * @enum {string}
       */
      status?: 'ACTIVE' | 'PAUSED' | 'CANCELLED';
      /**
       * @description 생성 시각 (ISO 8601 UTC Z)
       * @example 2026-05-25T13:00:00Z
       */
      createdAt?: string;
    };
    /** @description 정기 송금 목록 응답 (페이지) */
    ScheduledTransferListResponse: {
      /** @description 정기 송금 목록 */
      scheduledTransfers?: components['schemas']['ScheduledTransferListItem'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호 (0-base)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 건수
       * @example 2
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 1
       */
      totalPages?: number;
    };
    ApiResponseScheduledTransferHistoryResponse: {
      success?: boolean;
      data?: components['schemas']['ScheduledTransferHistoryResponse'];
      message?: string;
    };
    /** @description 정기 송금 회차 실행 이력 항목 */
    ScheduledTransferHistoryItem: {
      /**
       * @description 회차 거래 식별자(UUID)
       * @example c1d2e3f4-5678-90ab-cdef-1234567890ab
       */
      publicId?: string;
      /**
       * @description 송금 금액 (string 십진수)
       * @example 500000
       */
      amount?: string;
      /**
       * @description 출금 통화 코드
       * @example KRW
       */
      currencyCode?: string;
      /**
       * @description 수수료 (string 십진수)
       * @example 3000
       */
      fee?: string;
      /**
       * @description 수취 금액 (string 십진수)
       * @example 500000
       */
      receiveAmount?: string;
      /**
       * @description 수취 통화 코드
       * @example KRW
       */
      receiveCurrencyCode?: string;
      /**
       * @description 거래 상태 (현 단계는 COMPLETED만)
       * @example COMPLETED
       * @enum {string}
       */
      status?: 'COMPLETED' | 'FAILED';
      /**
       * @description 실행 시각 (ISO 8601 UTC Z) — transactions.created_at
       * @example 2026-05-25T12:00:00Z
       */
      executedAt?: string;
    };
    /** @description 정기 송금 회차 실행 이력 (페이지) */
    ScheduledTransferHistoryResponse: {
      /** @description 회차 실행 이력 목록 */
      histories?: components['schemas']['ScheduledTransferHistoryItem'][];
      /**
       * Format: int32
       * @description 현재 페이지 번호 (0-base)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 크기
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 건수
       * @example 3
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 1
       */
      totalPages?: number;
    };
    ApiResponseRecentRecipientsResponse: {
      success?: boolean;
      data?: components['schemas']['RecentRecipientsResponse'];
      message?: string;
    };
    RecentRecipientsResponse: {
      /** @description 최근 송금 수신자 목록 (수신자별 최신 송금 1건씩, 최근순) */
      receivers?: components['schemas']['RecipientItem'][];
    };
    RecipientItem: {
      /**
       * @description 수신자 회원 식별자(UUID)
       * @example 11111111-1111-1111-1111-111111111111
       */
      memberPublicId?: string;
      /**
       * @description 수신자 닉네임
       * @example Linh
       */
      nickname?: string;
      /**
       * @description 국적 코드
       * @example VN
       */
      nationality?: string;
      /**
       * @description 가장 최근 송금의 통화 코드
       * @example VND
       * @enum {string}
       */
      lastCurrencyCode?: 'KRW' | 'USD' | 'PHP' | 'VND';
      /**
       * @description 가장 최근 송금 시각(ISO 8601, UTC Z)
       * @example 2026-05-24T09:20:00Z
       */
      lastTransferredAt?: string;
      verified?: boolean;
      /**
       * @description 회원 인증 배지 여부
       * @example true
       */
      is_verified?: boolean;
    };
    AccountItem: {
      /**
       * @description 은행 코드
       * @example KOOKMIN
       */
      bankCode?: string;
      /**
       * @description 은행명
       * @example 국민은행
       */
      bankName?: string;
      /**
       * @description 마스킹된 계좌번호 (앞 3 + -****- + 뒤 4)
       * @example 123-****-1111
       */
      accountNumber?: string;
      /**
       * @description 수취인명 (송금 시점의 transactions.receiver_name)
       * @example 김민수
       */
      accountHolder?: string;
      /**
       * @description 가장 최근 송금의 통화 코드
       * @example KRW
       * @enum {string}
       */
      currencyCode?: 'KRW' | 'USD' | 'PHP' | 'VND';
      /**
       * @description 가장 최근 송금 금액 (소수점 4자리 string)
       * @example 200000
       */
      lastAmount?: string;
      /**
       * @description 가장 최근 송금 시각(ISO 8601, UTC Z)
       * @example 2026-05-24T09:20:00Z
       */
      lastTransferredAt?: string;
    };
    ApiResponseRecentAccountsResponse: {
      success?: boolean;
      data?: components['schemas']['RecentAccountsResponse'];
      message?: string;
    };
    RecentAccountsResponse: {
      /** @description 최근 송금 계좌 목록 (계좌별 최신 송금 1건씩, 최근순) */
      accounts?: components['schemas']['AccountItem'][];
    };
    ApiResponseExchangeListResponse: {
      success?: boolean;
      data?: components['schemas']['ExchangeListResponse'];
      message?: string;
    };
    ExchangeListResponse: {
      /** @description 환전 내역 목록(최근순) */
      exchanges?: components['schemas']['ExchangeResponse'][];
      /**
       * Format: int32
       * @description 현재 페이지(0부터)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지당 건수
       * @example 20
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 건수
       * @example 42
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수
       * @example 3
       */
      totalPages?: number;
    };
    AccountListResponse: {
      /** @description 등록된 활성 계좌 목록 (주 계좌 우선, 최신 등록순) */
      accounts?: components['schemas']['AccountResponse'][];
    };
    ApiResponseAccountListResponse: {
      success?: boolean;
      data?: components['schemas']['AccountListResponse'];
      message?: string;
    };
    ApiResponseSupportedBankListResponse: {
      success?: boolean;
      data?: components['schemas']['SupportedBankListResponse'];
      message?: string;
    };
    SupportedBankListResponse: {
      /** @description 지원 은행 목록 (활성화된 국내 은행, 이름 가나다순) */
      banks?: components['schemas']['SupportedBankResponse'][];
    };
    SupportedBankResponse: {
      /**
       * @description 은행 코드
       * @example 004
       */
      bankCode?: string;
      /**
       * @description 은행명
       * @example KB국민은행
       */
      bankName?: string;
    };
    AccountHolderResponse: {
      /**
       * @description Mock 은행에서 조회된 예금주 실명
       * @example 홍길동
       */
      accountHolderName?: string;
    };
    ApiResponseAccountHolderResponse: {
      success?: boolean;
      data?: components['schemas']['AccountHolderResponse'];
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  executeTransfer: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferExecuteRequest'];
      };
    };
    responses: {
      /** @description 송금 성공. 응답은 공통 ApiResponse로 감싸지며 data에 TransferExecuteResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTransferExecuteResponse'];
        };
      };
      /** @description COMMON4001 - Body 검증 실패 / TRANSFER4002 - 미지원 통화 / TRANSFER4003 - 미지원 송금 유형 / TRANSFER4004 - 자기 송금 / TRANSFER4005 - 미지원 통화 조합. 같은 400이지만 비즈니스 코드가 다르다 (examples 드롭다운 참고). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑 (송신자 또는 수신자 지갑·해당 통화 잔액 행 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4002 - 지갑 잔액이 부족합니다 (요청 형식은 정상이나 잔액 부족으로 처리 불가). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 분산 락 획득 실패(타임아웃/Redis 일시 장애). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: {
        status?: string;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 ScheduledTransferListResponse(scheduled_transfers 배열 + 페이지 메타)가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseScheduledTransferListResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다 (status 허용 enum 외 / page·size 범위 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateScheduledTransferRequest'];
      };
    };
    responses: {
      /** @description 설정 성공. data에 ScheduledTransferResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseScheduledTransferResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(필수 필드 누락·형식 오류·미지원 frequency) / TRANSFER4002 - 지원하지 않는 통화 / TRANSFER4003 - 지원하지 않는 송금 유형 / TRANSFER4004 - 자기 자신에게 송금할 수 없습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4006 - 인증되지 않은 계좌입니다(REMITTANCE — mock_account_token 미발급). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다(REMITTANCE) / WALLET4001 - 존재하지 않는 지갑입니다(INTERNAL — 수신자 wallet 부재). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4221 - 처리할 수 없는 요청입니다 (schedule_day 범위 초과 또는 currency != receive_currency). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  validateScheduled: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ValidateScheduledRequest'];
      };
    };
    responses: {
      /** @description 검증 자체는 성공. is_valid=true면 통과, false면 reason에 사유. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseValidateScheduledResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(필수 필드 누락·형식 오류) / TRANSFER4002 - 지원하지 않는 통화입니다 / TRANSFER4003 - 지원하지 않는 송금 유형입니다 / TRANSFER4004 - 자기 자신에게 송금할 수 없습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "COMMON4001",
           *       "message": "요청 값이 올바르지 않습니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "AUTH4011",
           *       "message": "인증이 필요합니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4006 - 인증되지 않은 계좌입니다(REMITTANCE — mock_account_token 미발급). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다(REMITTANCE — 본인 + active 미매칭) / WALLET4001 - 존재하지 않는 지갑입니다(INTERNAL — 수신자 wallet 부재). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "WALLET4001",
           *       "message": "존재하지 않는 지갑입니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "COMMON5000",
           *       "message": "서버 오류가 발생했습니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  setPin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferPinRequest'];
      };
    };
    responses: {
      /** @description PIN 설정 완료. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description COMMON4001 - PIN 형식 오류(숫자 6자리 아님). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4091 - 이미 송금 PIN이 설정되어 있습니다. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  verifyPin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferPinRequest'];
      };
    };
    responses: {
      /** @description 검증 성공. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description TRANSFER4007 - PIN 불일치 / TRANSFER4009 - PIN 미설정 / COMMON4001 - 형식 오류. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description TRANSFER4008 - 입력 횟수 초과로 잠김(10분). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getTransferFee: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferFeeRequest'];
      };
    };
    responses: {
      /** @description 계산 성공. 응답은 공통 ApiResponse로 감싸지며 data에 TransferFeeResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTransferFeeResponse'];
        };
      };
      /** @description COMMON4001 - Body 검증 실패 / TRANSFER4002 - 미지원 통화 / TRANSFER4003 - 미지원 송금 유형. 같은 400이지만 비즈니스 코드가 다르다 (examples 드롭다운 참고). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getExchanges: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseExchangeListResponse'];
        };
      };
      /** @description COMMON4001 - page/size 범위 위반. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  execute: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExchangeExecuteRequest'];
      };
    };
    responses: {
      /** @description 환전 완료. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseExchangeResponse'];
        };
      };
      /** @description EXCHANGE4002 - 환율 견적이 만료되었습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 접근 권한이 없습니다 (타인 견적으로 실행 시도). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description EXCHANGE4001 - 존재하지 않는 환전 내역입니다. (타인/타 유형의 idempotency_key 재사용 시 멱등 재반환을 차단 — 존재 미노출) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4002 - 지갑 잔액이 부족합니다. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createQuote: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuoteRequest'];
      };
    };
    responses: {
      /** @description 견적 발급 성공. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseQuoteResponse'];
        };
      };
      /** @description TRANSFER4002 - 지원하지 않는 통화입니다. / COMMON4001 - 요청 값 오류. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMyAccounts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. 응답은 공통 ApiResponse로 감싸지며 data에 AccountListResponse가 담긴다. 등록된 계좌가 없는 경우에도 200 + 빈 배열로 응답한다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountListResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  registerAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterAccountRequest'];
      };
    };
    responses: {
      /** @description 등록 성공. data에 AccountResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(필수값 누락/지원하지 않는 은행 코드). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4004 - 이미 등록된 계좌입니다. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 일시적으로 처리할 수 없습니다(등록 직렬화 분산락 획득 실패). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  charge: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChargeRequest'];
      };
    };
    responses: {
      /** @description 충전 성공. 응답은 공통 ApiResponse로 감싸지며 data에 ChargeResponse가 담긴다. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseChargeResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(금액 누락/형식 오류/0 이하, 필수 헤더 누락). / ACCOUNT4003 - 연동 계좌의 잔액이 부족합니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4006 - 인증되지 않은 계좌입니다(토큰 없음 또는 Mock 토큰 무효). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다. / WALLET4001 - 존재하지 않는 지갑입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4007 - 충전 한도를 초과했습니다. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(멱등성 일관성 위반 등 정상 불가 상태). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 일시적으로 처리할 수 없습니다(Mock 은행 통신 장애/타임아웃). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  verifyAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyAccountRequest'];
      };
    };
    responses: {
      /** @description 인증 성공. data.account_token 반환. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVerifyAccountResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다. / ACCOUNT4002 - 계좌 인증에 실패했습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4005 - 계좌 인증 요청 횟수를 초과했습니다(IP 단위 rate-limit). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 일시적으로 처리할 수 없습니다(Mock 은행 통신 장애). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  changePrimary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 변경 성공. data에 변경된 AccountResponse가 담긴다. 이미 주 계좌인 경우에도 멱등 200. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다(미존재/타인/비활성 계좌, 사유 구분 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 일시적으로 처리할 수 없습니다(계좌 변경 직렬화 분산락 획득 실패). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMyWallet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data 에 WalletMeResponse 가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseWalletMeResponse'];
        };
      };
      /** @description TRANSFER4002 - 지원하지 않는 통화(환율 미존재). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑(해당 사용자의 지갑 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMyTransactions: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 TransactionListResponse가 담긴다. 거래가 없으면 빈 배열. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTransactionListResponse'];
        };
      };
      /** @description COMMON4001 - page/size 범위 위반(page<0 또는 size 1~100 초과). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMyBalances: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. 응답은 공통 ApiResponse로 감싸지며 data에 WalletBalanceResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseWalletBalanceResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑(해당 사용자의 지갑 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getExchangeRates: {
    parameters: {
      query?: {
        /**
         * @description 조회할 통화 코드 콤마 구분 목록(예: USD,PHP,VND). 생략 시 KRW 제외 전체 지원 통화.
         * @example USD,PHP,VND
         */
        currency_codes?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data 에 ExchangeRateWidgetResponse 가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseExchangeRateWidgetResponse'];
        };
      };
      /** @description TRANSFER4002 - 지원하지 않는 통화(미지원 코드 입력 또는 환율 미존재). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getReceipt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transferPublicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 TransferReceiptResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTransferReceiptResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다(path variable 형식 위반). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "COMMON4001",
           *       "message": "요청 값이 올바르지 않습니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "AUTH4011",
           *       "message": "인증이 필요합니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description TRANSFER4001 - 존재하지 않는 송금 내역입니다. (미존재·본인 아님·미지원 유형 모두 동일 매핑) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "success": false,
           *       "code": "COMMON5000",
           *       "message": "서버 오류가 발생했습니다."
           *     }
           */
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  validateMember: {
    parameters: {
      query: {
        email: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 검증 성공. 응답은 공통 ApiResponse로 감싸지며 data에 ValidateMemberResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseValidateMemberResponse'];
        };
      };
      /** @description COMMON4001 - 이메일 형식 오류/누락. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description MEMBER4001 - 존재하지 않는 회원(해당 이메일의 앱 사용자 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getSupportedCurrencies: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. 응답은 공통 ApiResponse로 감싸지며 data에 SupportedCurrenciesResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSupportedCurrenciesResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getHistory: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path: {
        transferPublicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 ScheduledTransferHistoryResponse가 담긴다(회차 0건이면 빈 배열). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseScheduledTransferHistoryResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다 (page·size 범위 위반·path variable 형식). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description TRANSFER4001 - 존재하지 않는 송금 내역입니다 (미존재·본인 아님 동일 매핑). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getRecentInternalRecipients: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. 응답은 공통 ApiResponse로 감싸지며 data에 RecentRecipientsResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecentRecipientsResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑(해당 사용자의 지갑 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getRecentRemittanceAccounts: {
    parameters: {
      query?: {
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. 응답은 공통 ApiResponse로 감싸지며 data에 RecentAccountsResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseRecentAccountsResponse'];
        };
      };
      /** @description COMMON4001 - size 범위 위반(1~50). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description WALLET4001 - 존재하지 않는 지갑(해당 사용자의 지갑 없음). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getExchange: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseExchangeResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON4031 - 접근 권한이 없습니다. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description EXCHANGE4001 - 존재하지 않는 환전 내역입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getSupportedCurrencies_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data.currencies 로 지원 통화 목록 반환. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSupportedCurrenciesResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getSupportedBanks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. 응답은 공통 ApiResponse로 감싸지며 data에 SupportedBankListResponse가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSupportedBankListResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getAccountHolder: {
    parameters: {
      query: {
        bankCode: string;
        accountNumber: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공. data에 AccountHolderResponse(account_holder_name)가 담긴다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseAccountHolderResponse'];
        };
      };
      /** @description COMMON4001 - 요청 값이 올바르지 않습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 일시적으로 처리할 수 없습니다(Mock 은행 통신 장애). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공(soft-delete). data는 null이다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseVoid'];
        };
      };
      /** @description AUTH4011 - 인증이 필요합니다. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description ACCOUNT4001 - 존재하지 않는 계좌입니다(미존재/타인/이미 비활성 계좌). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5000 - 서버 오류(예상치 못한 예외). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
      /** @description COMMON5031 - 일시적으로 처리할 수 없습니다(계좌 변경 직렬화 분산락 획득 실패). */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
